name: dda_desktop
description: "A Dungeons and Dragons tool."
publish_to: 'none'

version: 0.0.1

environment:
  sdk: ^3.7.2

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  go_router: ^14.8.1
  flutter_signin_button: ^2.0.0
  crypto: ^3.0.6
  shelf: ^1.4.2
  shelf_router: ^1.1.4
  url_launcher: ^6.3.1
  logger: ^2.5.0
  google_fonts: ^6.2.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
  fonts:
    - family: OleoScript
      fonts:
        - asset: assets/fonts/OleoScript-Regular.ttf
        - asset: assets/fonts/OleoScript-Bold.ttf
